### PR TITLE
refactor: Move DSL Text methods to DSL::Text

### PR DESCRIPTION
**Pull request by OrthoDex**
Shifted the text methods to another file within a new directory 'dsl'.

How does this look @PragTob @jasonrclark ?

### CODE REVIEW

**Comment by jasonrclark** [comment]
Hey @OrthoDex, the code here is looking good to me.

There is a failure in the build from Rubocop which wants a frozen string literal comment at the top and some slightly different spacing. You can run locally to see these failures by executing `rubocop`, but I've logged #1392 so the default Rake task also runs it so folks will have a better chance of catching these type of things before CI.

Once that's tidied up, this should be 👌 for merging.

**Comment by OrthoDex** [comment]
Hey @jasonrclark ,

rake spec:core is running successfully on my local machine,I dunno why there is a NullPointerException. :thinking:

**Comment by jasonrclark** [comment]
@OrthoDex That's totally an odd failure... looks like an underlying JRuby thing? I've bumped it to rebuild and if we're all good, will merge this evening when I get down to my shoes time. Thank you!

**Comment by jasonrclark** [comment]
Looking good, thanks again @OrthoDex!

For future PRs of this type you can either do them one by one or group things together if you'd rather. I would appreciate the individual commits per move to make it easier to review in batch.

✨

**Comment by OrthoDex** [comment]
Thank you so much @jasonrclark ! :smile: 

I was thinking of doing small commits, squashing them in one commit per extraction and then issuing a PR for the entire thing.

If you would like to merge the extractions as they come, I can issue individual PRs for each extraction. I think we can then track the code climate status as the extractions come.
Thoughts?

**Comment by jasonrclark** [comment]
One PR with each extraction as a commit sounds 👌 for me.

If at any point you need to pause, don't feel like you need to hold the rest until it's all there, just push a PR.

Feels like a PR per extraction is just busy-work, but I deeply appreciate keeping the individual commits for diffing.

**Comment by OrthoDex** [comment]
Got it!
I'll issue a PR soon, and add commits as I start extracting the methods. :smile:

**Pull request merged**
