### PR TITLE
Appveyor

### PR DESCRIPTION
**Pull request by PragTob**
loads of time pourted into this, after they were so nice to install jruby 9k on their systems with bundler preinstalled (it used to time out on installing bundler) this seems/should work fine.

### CODE REVIEW

**Comment by PragTob** [comment]
It... works :sunglasses:

**Comment by KCErb** [comment]
Woohoo! :tada:

**Comment by PragTob** [comment]
I'll give this a merge than! :D

**Comment by jasonrclark** [comment]
:dancer:

**Pull request merged**
