### PR TITLE
Rubocop: Fix all double negation

### PR DESCRIPTION
**Pull request by jaredmoody**
How’s this look?

### CODE REVIEW

**Comment by PragTob** [comment]
Hmm, form an introspection point of view I'd like the variable to be a boolean.

How about...  `@fixed_height = !height.nil?` and then just remove the `!!` ? Does this work? Otherwise we could also do something like `@variable_height = height.nil?` and then adjust the methods

**Comment by jasonrclark** [comment]
Does anything other than these predicate methods is @fixed_height? On phone so I can't search easily but I don't see use in the file, or att exposure.

If that's the case, how about just one nil? check in initialize and then the predicates are just pure returns?

**Comment by PragTob** [comment]
@jasonrclark was the only usage I could find, I'm with you there one nil check in initialize :)

**Comment by jasonrclark** [comment]
❤️

**Pull request merged**
