### PR TITLE
CI against JRuby 9.1.9.0

### PR DESCRIPTION
**Pull request by PragTob**
See if we run into the each_with_index problem outlined in jruby/jruby#4610

### CODE REVIEW

**Comment by jasonrclark** [comment]
Do we want to change the `.ruby-version` as well in lock step? Or just do this in CI until 9.1.10.0 is out?

**Comment by PragTob** [comment]
ah most definitely, good catch.

**Comment by jasonrclark** [comment]
Looks like I waited too long and 9.1.10.0 came out #1434 😆

**Comment by PragTob** [comment]
Yeah 9.1.10 fixed the exact regression :)

**Pull request closed without merging**
