### PR TITLE
Extract element styling

### PR DESCRIPTION
**Pull request by OrthoDex**
Hey @PragTob ,
This is what I had in mind for element styling.

An AppStyle module could hold #nostroke, #nofill, and other constants.

Part of #1341

### CODE REVIEW

**Comment by PragTob** [comment]
Heyho, I think this is missing the removal of the code from `dsl.rb` :)

If it's just one method, I'm thinking it's fine to live with other style related methods in App::Style or whatever but not sure. Maybe @jasonrclark has some input :)

**Comment by OrthoDex** [comment]
Ahh, I had forgotten to add that to the commit.

Sorry about the sloppy work :disappointed_relieved:

**Comment by jasonrclark** [comment]
Hmm, I think I'd be inclined to just roll with a single `DSL::Style` that includes both app and element stuff. It's all somewhat inter-related, and not enough code to make that single module overwhelmingly large.

Love the stuff you've been churning out this weekend @OrthoDex! Thank you.

**Comment by OrthoDex** [comment]
Hey @PragTob , @jasonrclark
Does this look alright?

**Comment by PragTob** [comment]
It does, thank you!

**Pull request merged**
