### PR TITLE
Introduce Code of Conduct for the Shoes project

### PR DESCRIPTION
**Pull request by jasonrclark**
Hey all!
One of the best things about Shoes is how welcoming and open it is. It's been an awesome place for me to grow as an open source contributor, and I'd like to see it stay that way.

For many people, an explicit code of conduct is part of creating a safe environment online. I'd like to propose that we adopt one. The text here was drawn from the excellent http://contributor-covenant.org.

I'm super glad that we haven't had any significant problems to date, but that's all the more reason to put one in place now. With it, there are clearly stated expectations of how people will be treated when interacting with Shoes, and how the maintainers will handle issues that might arise in the future.

Obviously this is a big change to introduce well after a project has started, but I hope that we can come together on it. @PragTob @wasnotrice @KCErb @steveklabnik, what do you all think?

### CODE REVIEW

**Comment by steveklabnik** [comment]
Big :+1:  from me

**Comment by ccoupe** [comment]
Really? Not my project so I've no skin to lose either way but pre-emptive PC speech  (of the day) censorship rankles me or does 'rankle' not translate into other languages without a gender adjective or pronoun or modifier?

Yes, English is a barrier and colloquialisms and cultural slang don't help, but srly? A pledge and everything will be good?

**Comment by wasnotrice** [comment]
@jasonrclark I really like it. I made a couple of comments inline...

@ccoupe curious as to which part(s) of the pledge you have issues with. I've never known you to cause or wish to cause offense to anyone, especially by personal attack. To my reading, this is a very bare-bones, non-specific pledge that basically only says "you can be assured that when you get involved with Shoes, nobody is going to attack you for who you are, no matter what." And that's worth saying, IMO. It's not about English being a barrier—it's about lack of respect for individuals being a barrier.

**Comment by KCErb** [comment]
I really like @wasnotrice's changes! 

Anything that takes this in a direction of: Have Fun with Shoes. And away from: here's the Sexual Harassment clause at the end of your signing contract.

As for the nature of such a document (which I interpret @ccoupe's comments to be aimed at) I too have mixed feelings. It doesn't seem likely that a future malefactor in this regard will actually alter their interactions with us after being pointed to a code of conduct document. So if we don't expect it to actually impact behavior, then it feels more like a symbolic declaration of common beliefs. And that's why I'd rather it felt more like a declaration than a contract :)

So basically I fall along two lines: if the intent is to have a contract, and more experienced project maintainers than me feel that such a contract (covenant) has a positive impact on a project like ours, then I'm fine with this being a part of Shoes 4 as is.

If the intent is to have a declaration of common beliefs, then I want it to sound more fun and Shoesy! 

My introduction to the Ruby community was through Shoes. I was consistently impressed by the community's easy-going attitude and newcomer-friendly responses to all of my questions. I've worked with the MATLAB community, python community, Android community and have seen a lot of rude responses aimed at attacking the experience-level of would-be programmers. But Ruby developers, and especially Team Shoes members, were consistently kind and helpful and made me want to keep trying. I loved that, and if members of the community feel that something to that effect should be put into writing instead of trusting it to be passed on experientially, then that's fine with me.

I'd like something in this direction:

**code_of_conduct.md**

> Way way back in the day, there was a guy named _why. He created a project known as Hackety Hack to teach programming to everyone. In order to reach all corners of the earth, _why decided to make Hackety Hack work on Windows, Mac OS X, and Linux. This was a lot of work, and so _why decided to share his toolkit with the world. Thus, Shoes was born.

> This heritage is the basis of our code of conduct. Shoes was born to teach programming to everyone, in all corners of the earth. It's not cool to make new programmers or programmers with bad English feel bad because they don't write Ruby / English very well. And it should go without saying that any other anti-social comments directed at someone's religion, ethnicity, race, gender identity, or any of that personal stuff won't be tolerated here in the land of chunky-bacon! If community members feel like your comments are out of line, they'll *kindly* let you know how to improve.

> The bottom-line is: Have Fun with Shoes!

**Comment by ccoupe** [comment]
These conversions tend to follow a path. Symbolic gesture or statement is proposed, discussions on wording &  meaning & motives... and at least one person questioning the wisdom of solving a non-existing problem with a non-binding document only the writers will read.  Been there, too many times. This time I'm that last guy. Sometimes doing nothing is the best course of action.

**Comment by jasonrclark** [comment]
Thanks all for the comments.

@KCErb I really like the Shoesy tone of what you've written! That said, I *do* actually view this more on the contract end of the spectrum. While it won't stop someone from acting poorly, it does clearly state my responsibilities as a project maintainer to speak up (which I'd find harder if nothing had been said before). Because of that, I'd like to keep the main doc as it stands, but your bit would be a much better intro in the README. What do you think?

@wasnotrice Totally happy to put the main doc back to the original. I poached that line off the website to try it on for size, so I'll whack it when I push the next rev.

**Comment by KCErb** [comment]
Sounds fine to me @jasonrclark!

**Comment by PragTob** [comment]
As mentioned offlien with Jason ebfore, big :+1: from my side! :) Let's work those last changes in and :shipit: 

PS: @wasnotrice @steveklabnik happy to see you're still watching the repo sort of closely and chime in on important issues :heart:

**Comment by PragTob** [comment]
@jasonrclark good tog o now? :)

**Comment by jasonrclark** [comment]
Integrated the text from @wasnotrice and @KCErb into the README, and restored the main doc to it's plain, original form. Ready to go?

**Comment by PragTob** [comment]
:+1:

**Comment by PragTob** [comment]
I'll just pull the trigger, we can make adjusments later if really necessary. Thanks everyone.

**Comment by jasonrclark** [comment]
Thanks @PragTob! :heart:

**Pull request merged**
