### PR TITLE
Add missing gem furoshiki;

### PR DESCRIPTION
**Pull request by MichaelDimmitt**
Not sure if it was missing, or removed on purpose.
I had to bring "gem furoshiki" in to get shoes4 working on my computer.

Macintosh environment:  Sierra Operating System.
Using current standard jruby-9.1.8.0 [ x86_64 ]
Relates to issue #291

### CODE REVIEW

**Comment by jasonrclark** [comment]
Hey @MichaelDimmitt!

`furoshiki` is a dependency of `shoes-package`, which pulled in by `shoes-swt`, so something interesting is going on with your setup.

Are you trying to run shoes from source (i.e. cloned off GitHub) or via `gem install --pre shoes`?

If you're working from source, a `bundle install` in the directory should have installed `furoshiki`

In either case, can you provide the output of `ruby -v` and `gem list`?

**Comment by MichaelDimmitt** [comment]
sure, this should give you all the information you need:
<pre>
[michaeldimmitt]🙂 
dir: ~
git clone https://github.com/shoes/shoes4.git
Cloning into 'shoes4'...
remote: Counting objects: 30631, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 30631 (delta 3), reused 0 (delta 0), pack-reused 30621
Receiving objects: 100% (30631/30631), 54.51 MiB | 935.00 KiB/s, done.
Resolving deltas: 100% (21938/21938), done.
[michaeldimmitt]🙂 
dir: ~
cd shoes4/
[michaeldimmitt]🙂 
dir: ~/shoes4
bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies.......
Using rake 12.0.0
Using public_suffix 2.0.5
Using after_do 0.4.0
Using ast 2.3.0
Using benchmark-ips 2.7.2
Using bundler 1.14.6
Using docile 1.1.5
Using json 2.1.0 (java)
Using simplecov-html 0.10.0
Using coderay 1.1.1
Using safe_yaml 1.0.4
Using diff-lcs 1.3
Using ffi 1.9.18 (java)
Using formatador 0.2.5
Using plist 3.3.0
Using rubyzip 1.2.1
Using jruby-jars 9.1.8.0
Using jruby-rack 1.1.20
Using rb-fsevent 0.9.8
Using ruby_dep 1.5.0
Using lumberjack 1.0.11
Using nenv 0.3.0
Using shellany 0.0.1
Using method_source 0.8.2
Using slop 3.6.0
Using thor 0.19.4
Using guard-compat 1.2.1
Using rspec-support 3.5.0
Using hashdiff 0.3.4
Using hometown 0.2.5
Using kramdown 1.13.2
Using nokogiri 1.6.4.1 (java)
Using powerpack 0.1.1
Using ruby-progressbar 1.8.1
Using unicode-display_width 1.2.1
Using shoes-core 4.0.0.pre9 from source at `shoes-core`
Using shoes-highlighter 1.0.1
Using swt 4.6.1.1
Using yard 0.9.9
Using rainbow 2.2.2
Using addressable 2.5.1
Using parser 2.4.0.0
Using simplecov 0.13.0
Using crack 0.4.3
Using rb-inotify 0.9.8
Using spoon 0.0.6
Using warbler 2.0.4
Using notiffany 0.1.1
Using rspec-core 3.5.4
Using rspec-expectations 3.5.0
Using rspec-mocks 3.5.0
Using shoes-manual 4.0.1
Using rubocop 0.47.1
Using codeclimate-test-reporter 1.0.8
Using webmock 3.0.1
Using listen 3.1.5
Using pry 0.10.4 (java)
Using furoshiki 0.4.0
Using rspec-its 1.2.0
Using rspec 3.5.0
Using guard 2.14.1
Using pry-nav 0.2.4
Using shoes-package 4.0.0.pre9 from source at `shoes-package`
Using guard-rspec 4.7.3
Using shoes-swt 4.0.0.pre9 from source at `shoes-swt`
Using shoes 4.0.0.pre9 from source at `.`
Bundle complete! 22 Gemfile dependencies, 66 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
[michaeldimmitt]🙂 
dir: ~/shoes4
rvm list

rvm rubies

   jruby-9.1.7.0 [ x86_64 ]
=> jruby-9.1.8.0 [ x86_64 ]
   ruby-2.1.0 [ x86_64 ]
   ruby-2.1.5 [ x86_64 ]
 * ruby-2.4.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

[michaeldimmitt]🙂 
dir: ~/shoes4
vi Gemfile
[michaeldimmitt]🙂 
dir: ~/shoes4
bin/shoes package --mac samples/simple_sound.rb 
Selecting shoes-swt backend to use. This is a one-time operation.
Packaging mac...
LoadError: no such file to load -- furoshiki/windows_app
          require at org/jruby/RubyKernel.java:961
  create_packager at /Users/michaeldimmitt/shoes4/shoes-package/lib/shoes/package.rb:7
     block in run at /Users/michaeldimmitt/shoes4/shoes-swt/lib/shoes/swt/packager.rb:41
             each at org/jruby/RubyArray.java:1734
              run at /Users/michaeldimmitt/shoes4/shoes-swt/lib/shoes/swt/packager.rb:39
              run at /Users/michaeldimmitt/shoes4/shoes-core/lib/shoes/packager.rb:23
              run at /Users/michaeldimmitt/shoes4/shoes-core/lib/shoes/ui/cli/package_command.rb:13
              run at /Users/michaeldimmitt/shoes4/shoes-core/lib/shoes/ui/cli.rb:37
           <main> at /Users/michaeldimmitt/shoes4/shoes-swt/bin/shoes-swt:12
             load at org/jruby/RubyKernel.java:979
           <main> at /Users/michaeldimmitt/shoes4/bin/shoes-swt:6
[michaeldimmitt]😞 
dir: ~/shoes4
</pre>

**Comment by jasonrclark** [comment]
Ah, that makes better sense now. The actual error message at the last was the key--I've made changes in `furoshiki` that aren't released yet but which Shoes relies on in `master`. Had forgotten about that 😆 

When I run it with your change as listed, I get the following warning on `bundle install`

```
The git source `git://github.com/shoes/furoshiki.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
```

I'd rather it run without those type of alarming messages, so could you change the line to include it via this instead:

```
gem 'furoshiki', git: 'https://github.com/shoes/furoshiki'
```

**Comment by MichaelDimmitt** [comment]
I made the change. It looks like you have also made file changes.
Is that correct? I want to make sure those changes were not my doing.
All I changed was the Gemfile.

**Comment by jasonrclark** [comment]
Hmm, looks like removing commits got things a little mixed up. Those are earlier commits in Shoes, but it's saying they're "with MichaelDimmitt" which sounds to me like a rebase/rewrite gone awry.

If you know how to do it, I'd recommend that you get master pointed back to the same commit as the main shoes4 repo, then cherry-pick your commit. Happy to help further with that if you need a hand.

(FWIW, it looks like you're working against `master` in your own repo. You'll probably have less problems in the future if you create a separate branch to work against like `git checkout -b my-working-branch`, and then PR from that).

**Comment by MichaelDimmitt** [comment]
I did rebase back to remove the errant commit. 
I will re-fork make the commit and push.
But I may have to make a new pull request.
thank you for the tips.

**Comment by MichaelDimmitt** [comment]
made a new pull request #1424

**Pull request closed without merging**
