### PR TITLE
Less git, more lists

### LINKED ISSUE #1226: Installing Shoes 4 from github failed
I'am try to install shoes4 from source and occurred an error .
First I download the source from github.
Then >cd  D:\tools\ruby\shoes\shoes4_src\shoes4-master
And run >rake install:all it output the following error

```
D:\tools\ruby\shoes\shoes4_src\shoes4-master>rake install:all
cd ./shoes-core && rake install
fatal: Not a git repository (or any of the parent directories): .git
shoes-core 4.0.0.pre5 built to pkg/shoes-core-4.0.0.pre5.gem.
rake aborted!
Couldn't install gem, run `gem install D:/tools/ruby/shoes/shoes4_src/shoes4-mas
ter/shoes-core/pkg/shoes-core-4.0.0.pre5.gem' for more detailed output
D:\jruby-9.0.5.0\bin\rake:23:in `<top>'
Tasks: TOP => install
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [cd ./shoes-core && rake install...]
D:/tools/ruby/shoes/shoes4_src/shoes4-master/tasks/gem.rb:22:in `block in (root)
'
D:\jruby-9.0.5.0\bin\rake:23:in `<top>'
Tasks: TOP => install:all => install:shoes-core
(See full trace by running task with --trace)
```

After that I try >jruby -S gem install D:\tools\ruby\shoes\shoes4_src\shoes4-master\shoes-core\pkg\shoes-core-4.0.0.pre5.gem

```
Building native extensions.  This could take a while...
ERROR:  Error installing D:\tools\ruby\shoes\shoes4_src\shoes4-master\shoes-core
\pkg\shoes-core-4.0.0.pre5.gem:
        ERROR: Failed to build gem native extension.

    D:/jruby-9.0.5.0/bin/jruby.exe -rubygems D:/jruby-9.0.5.0/lib/ruby/gems/shar
ed/gems/rake-10.5.0/bin/rake RUBYARCHDIR=D:/jruby-9.0.5.0/lib/ruby/gems/shared/e
xtensions/universal-java-1.7/2.2.0/shoes-core-4.0.0.pre5 RUBYLIBDIR=D:/jruby-9.0
.5.0/lib/ruby/gems/shared/extensions/universal-java-1.7/2.2.0/shoes-core-4.0.0.p
re5
rake aborted!
Errno::ENOENT: No such file or directory - D:/jruby-9.0.5.0/lib/ruby/gems/shared
/gems/shoes-core-4.0.0.pre5/ext/install/shoes.bat

Tasks: TOP => default => install_script
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in D:/jruby-9.0.5.0/lib/ruby/gems/shared/gems/sh
oes-core-4.0.0.pre5 for inspection.
Results logged to D:/jruby-9.0.5.0/lib/ruby/gems/shared/extensions/universal-jav
a-1.7/2.2.0/shoes-core-4.0.0.pre5/gem_make.out
```

Here is my env
OS: Windows 7
jruby: jruby 9.0.5.0
shoes: have already installed 4.0.0.pre5 (does this takes any effect？)

### PR DESCRIPTION
**Pull request by jasonrclark**
Fixes #1226 and related to https://github.com/shoes/furoshiki/pull/22

This goes with option 2) I presented there--using `Dir` to list files instead of relying on git.

I've done a fair amount of comparison work locally, and [here's a snapshot](http://jasonrclark.com/shoes-compare.html) from my favorite diffing program (Beyond Compare) showing the diffs. Purple stuff is "orphaned" so you can see what we're dropping on the right. Empty + red + gray just has file diffs potentially, but no mismatched files.

I've chosen to drop the `spec` folder from the projects, as it's not required and just bulks things up.

Also updates some other bits of the gemspec I noticed were out of date.

I'll be doing some thorough testing of the generated gems before merging this, but don't have the time at the moment.

image

## TODO

* [x] Check gem installation and samples on:
  * [x] Mac
  * [x] Linux (Ubuntu)
  * [x] Windows
* [x] Check packaging with hacked install on Mac (still pending work to get it working properly out-of-the-box)

### CODE REVIEW

**Comment by PragTob** [comment]
LGTM... although I'm not quite sure why we need the static stuff beyond the shoes logo? The downloading image could also be text? I'm confused. A bit.

**Comment by jasonrclark** [comment]
Yeah those extra logos could go for sure. Keep things trim.

On the download image, I think it's mainly because that class knows how to draw images rather than text... Might I could see whether changing that to put text in, or spicing up the image some. Will ponder.

**Comment by PragTob** [comment]
@jasonrclark that's also totally something for another PR and day, sorry for putting it in :D

**Comment by jasonrclark** [comment]
No sorries at all :) Didn't feel like you were suggesting the PR can't ship without resolving it, and I didn't even look at the images we were including until you pointed them out.

**Comment by jasonrclark** [comment]
Testing came through clean on all the OSs. Think I'll roll forward with it since we're a good ways from `pre8` shipping and I'll be doing plenty more gem testing before that gets out the door if there are any lurking 🐞

**Pull request merged**
